config/routes.rb
Rails.application.routes.draw do

  resources :images
  #devise_for :users, :controllers => { registrations: 'registrations' }
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy' end


  post 'user/create' => 'users#create'

  post 'authenticate' => 'users#login_verify'
  get 'products' => 'products#list'
  post 'product/update/:id' => 'products#update'
  patch 'product/update/:id' => 'products#update'
  get 'product/edit/:id' => 'products#edit'
  get 'product/new' => 'products#new'
  post 'product/create' => 'products#create'
  get 'product/:id' => 'products#show'
  get 'search_product' => 'products#search'

  get 'user/profile' => 'users#profile'
  post 'update_profile' => 'users#update'
  patch 'user/:id/update_profile' => 'users#update'

  get 'basket/put' => 'baskets#put'
  get 'basket/put_resume' => 'baskets#put_resume'
  get 'basket/cancel_product/:product_id' => 'baskets#cancel_product'
  get 'basket/show/:id' => 'baskets#show'
  get 'basket' => 'baskets#basket'
  get 'basket/index' => 'baskets#index'
  get 'basket/reset' => 'baskets#reset_basket'
  get 'basket/basket_details' => 'baskets#basket_details'
  get 'basket/basket_modal' => 'baskets#basket_modal'



  get 'products/csv' => 'products#export_to_csv'

  get 'categories/:id' => 'categories#show'
  get 'categories' => 'categories#list'

  root 'products#list'

end

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Basket < ActiveRecord::Base
  has_and_belongs_to_many :products
  belongs_to :user

  def total_price
    products = Product.in_basket(self)
    total_price = 0
    products.each do |product|
      product_in_basket = BasketsProduct.find_by(basket_id: self.id, product_id: product.id)
      total_price += product_in_basket.quantity * Product.find(product_in_basket.product_id).price
    end
    total_price
  end

  def products_quantities
    products_in_baskets = BasketsProduct.where(basket_id: self.id)
    quantities = Hash.new

    products_in_baskets.each do |product|
      quantities[product.product_id] = product.quantity
    end
    quantities
  end

  def put(product_id, quantity)
    basket_product = BasketsProduct.find_by(product_id: product_id, basket_id: self.id)

    if(basket_product.nil?)
      self.products.push(Product.find(product_id))
      self.save
      basket_product = BasketsProduct.find_by(product_id: product_id, basket_id: self.id)
      basket_product.quantity  = quantity
      basket_product.save
    else
      basket_product.quantity += quantity.to_i
      basket_product.save
    end
  end
end

app/controllers/baskets_controller.rb
# == Schema Information
#
# Table name: baskets
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy, :put, :basket_details, :cancel_product, :put_resume, :basket_modal, :reset_basket]

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    @products = Product.all
    @quantities = @basket.products_quantities

    render :show, layout: nil
  end

  def basket
  end

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # GET /baskets/1/edit
  def edit
  end

  def put
    @basket.put(params[:product_id], params[:product_quantity])
    respond_to do |format|
      format.html { redirect_to action: 'show', id: @basket.id }
    end
  end

  def basket_modal
    render :basket_modal, layout: nil
  end

  def put_resume
    @basket.put(params[:product_id], params[:product_quantity])
    @quantities = @basket.products_quantities
    render :basket_details, layout: nil
  end

  def basket_details
    @quantities = @basket.products_quantities
    render :basket_details, layout: nil
  end

  def reset_basket
    @basket.products.delete_all
    @basket.save
    render :basket_details, layout: nil
  end

  def cancel_product
    @basket.products.destroy(Product.find(params[:product_id]))

    respond_to do |format|
      if @basket.save
        format.html { redirect_to action: 'list', controller: 'products', notice: 'Product was successfully canceled' }
      else
        format.html { render :list }
      end
    end
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_basket
    if !current_user.nil?
      @basket = current_user.basket
      @categories = Category.all
      @total_price = @basket.total_price
    else
      redirect_to '/users/sign_up'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def basket_params
    params.require(:basket).permit(:id, :quantity)
  end
end

app/helpers/baskets_helper.rb
# == Schema Information
#
# Table name: baskets
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module BasketsHelper
end

app/views/baskets/_basket_details.html.erb
<div class="panel panel-success">
<div class="panel-heading">My Basket</div>

  <div class="panel-body">

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Cancel</th>
        </tr>
    </thead>
    <tbody>
        <% @basket.products.each do |product| %>
            <tr>
                <td><%= link_to "#{product.name}", action: 'show', controller: '/products', id:product.id %></td>
                <td><%= @quantities[product.id]%></td>
                <td><%= link_to  action: 'cancel_product', controller: '/baskets', product_id:product.id do%>
                        <button class="btn btn-danger">Cancel</button>
                    <%end%>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

</div>
  <div class="panel-footer">    <h3 > Total price : <small> <%= @total_price.round(2) %> </small>
  <button id="reset_basket" class="btn btn-warning">Reset Basket</button></h3>
 </div>

</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#test">
  More details >>
</button>
<%= link_to action: 'export_to_csv', controller:'/products', format: 'csv' do %>
    <button class="btn btn-warning"> <i class="fa fa-floppy-o"></i>CSV</button>

<% end %>

app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/_show.html.erb
<table class="table">
<caption>My Basket</caption>
    <thead>
        <tr>
            <th>Image</th>
            <th>Products ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Cancel</th>
        </tr>
    </thead>
    <tbody>
        <% @basket.products.each do |product| %>
            <tr>
                <td><%= image_tag product.photo.url(:small) %></td>
                <td><%= link_to "#{product.name}", action: 'edit', controller: '/products', id:product.id %></td>
                <td><%= product.name %></td>
                <td><%= product.price %></td>
                <% @quantities = @basket.products_quantities %>
                <td><%= @quantities[product.id]%></td>
                <td><%= link_to  action: 'cancel_product', controller: '/baskets', product_id:product.id do%>
                        <button class="btn btn-danger">Cancel</button>
                    <%end%>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

<% if !@basket.nil? %>
    <h3 > Total price : <small> <%= @total_price %> </small> </h3>
<%end%>

app/views/baskets/basket_details.html.erb
<div class="panel panel-success">
<div class="panel-heading">My Basket</div>

  <div class="panel-body">

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Cancel</th>
        </tr>
    </thead>
    <tbody>
        <% @basket.products.each do |product| %>
            <tr>
                <td><%= link_to "#{product.name}", action: 'show', controller: 'products', id:product.id %></td>
                <td><%= @quantities[product.id]%></td>
                <td><%= link_to  action: 'cancel_product', controller: '/baskets', product_id:product.id do%>
                <button class="btn btn-danger">Cancel</button>
                <%end%>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

</div>
 <div class="panel-footer">    <h3 > Total price : <small> <%= @total_price.round(2) %> </small>
  <button id="reset_basket" class="btn btn-warning">Reset Basket</button></h3>
 </div>

</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#test">
  More details >>
</button>
<%= link_to action: 'export_to_csv', controller:'/products', format: 'csv' do %>
    <button class="btn btn-warning"> <i class="fa fa-floppy-o"></i>CSV</button>
<% end %>

app/views/baskets/basket_modal.html.erb
<%= render '/baskets/show' %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<div class="panel panel-success">
<div class="panel-heading">My Basket</div>

  <div class="panel-body">

<table class="table">
<caption>My Basket</caption>
    <thead>
        <tr>
            <th>Image</th>
            <th>Products ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Cancel</th>
        </tr>
    </thead>
    <tbody>
        <% @basket.products.each do |product| %>
            <tr>
                <td><%= image_tag product.photo.url(:small) %></td>
                <td><%= link_to "#{product.name}", action: 'edit', controller: 'products', id:product.id %></td>
                <td><%= product.name %></td>
                <td><%= product.price %></td>
                <td><%= @quantities[product.id]%></td>
                <td><%= link_to  action: 'cancel_product', controller: '/baskets', product_id:product.id do%>
                        <button class="btn btn-danger">Cancel</button>
                    <%end%>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

<% if !@basket.nil? %>
    <h3 > Total price : <small> <%= @total_price %> </small> </h3>
<%end%>

</div>
  <div class="panel-footer">Panel footer</div>
</div>

<a class="back-to-top" href="#top">tttttttttt</a>